# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       libgato

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    A GATT library to connect with Bluetooth Smart devices
Version:    0.1.4
Release:    1
Group:      Qt/Qt
License:    GPL2
URL:        https://gitorious.org/gato/
Source0:    %{name}-%{version}.tar.bz2
Source100:  libgato.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(bluez)

%description
Gato is a library implementing a GATT/ATT client (central) designed to connect
Qt programs with Bluetooth Smart (also known as Low Energy) devices.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for %{name}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/libgato.so.1
%{_libdir}/libgato.so.1.0
%{_libdir}/libgato.so.1.0.0
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/gato
%{_libdir}/libgato.so
# << files devel
